### ISSUE TITLE
Async support for CRUD operations

### ISSUE THREAD

**Issue by aleq** [sapiens/SqlFu#29]
Add support for async CRUD operations

**Comment by karthik25** [comment]
Looks like this is already done! Probably should be closed!! Found this on up-for-grabs and was eager to do it :)

**Comment by sapiens** [comment]
What? Where? There is nothing Insert/Update/Delete async

**Comment by karthik25** [comment]
Ah, you're right, I looked at the file completely, it isn't there! Let me see if I can contribute, thanks!

**Comment by sapiens** [comment]
Cool, don't forget to target the 'devel' branch in the PR .

**Comment by sapiens** [comment]
done in ver 3
