### ISSUE TITLE
Advanced query support with lambda expressions

### ISSUE THREAD

**Issue by aleq** [sapiens/SqlFu#48]
Let's assume we have the following entities (traditional Order/OrderDetail screnario)

public class Order 
{
public int Id {get;set};
}

public class OrderDetail
{
public int Id{get;set;}
public int OrderId{get;set;}
public int ProductId{get;set;}
}

Very often we will need to search by one of the many-2-one / one-2-one relations in this case - possibility to filter Order entities by ProductId without having to write manual sql query or using stored procedure.

**Comment by sapiens** [comment]
I don't plan to go the orm route, probably this won't happen.
