### ISSUE TITLE
QueryOnly seems not to work

### ISSUE THREAD

**Issue by bxbxbx** [sapiens/SqlFu#56]
According to the docs the QueryOnly Attribute should prevent write access of the column.
But it seems that it also prevents the reading of the column, because in my case the columns is always null.

In the class ```ExpressionSqlBuilder``` in the method

    public ExpressionSqlBuilder<T> WriteSelectAllColumns()

is the following line                 

    if (_ti.Excludes.Contains(c)) continue;

This seems wrong to me.
The accompaning test seems not to fail because of the unfortunate default value 0 of the column.

**Comment by sapiens** [comment]
If you're certain it's a bug, I'm accepting PRs

**Comment by sapiens** [comment]
Fixed in release 2.3.7
