### ISSUE TITLE
OnCommand not work

### ISSUE THREAD

**Issue by davidhxy678** [sapiens/SqlFu#57]
When I want to set the CommandTimeout like this way,SqlFuDao.OnCommand = cmd => cmd.CommandTimeout = 120,OnCommand  not work.
I read the source code,and find that in the sqlFu.sqlFuDao.cs  GetRawValue() ,
OnCommand(cmd) need to put front of the  rez = cmd.ExecuteScalar(),Is it that right?

**Comment by sapiens** [comment]
OnCommand  is meant for logging purposes. What you want is 

```csharp
db.WithSql(sql,args).Apply(cmd=>cmd.CommandTimeout = 120 ).Query<MyType>()
```

**Comment by davidhxy678** [comment]
thanks.Howerver,if I want to use CrudHelpers.Insert,how to set the CommandTimeout?

**Comment by sapiens** [comment]
Currently, there aren't any helpers that accept configuration of DbCommand. I'll add that in the future
