### ISSUE TITLE
Test Connection Strings should be configurable

### ISSUE THREAD

**Issue by wolfascu** [sapiens/SqlFu#71]
Currently, the SQL Connection Strings used for the tests are [hardcoded in the src/Test/Config.cs file](https://github.com/sapiens/SqlFu/blob/f05296433d45cad32d5221044b630a1b240e7730/src/Tests/Config.cs#L13-L16).

Not all contributors have a local database instance with the same name/credentials and I think it would be nice to provide some minimal flexibility in this case.

My idea would be to use some predefined [ConnectionStrings](https://msdn.microsoft.com/en-us/library/ms254494(v=vs.110).aspx) settings that every developer would be able to configure in his/her local machine.config file. In case any of the necessary connection strings are not defined, we should fall back to the default (hardcoded) ones.

**Comment by sapiens** [comment]
I get what you're saying, but at this moment I think it doesn't bring any benefits. To be honest, I doubt that many developers would change their machine.config (which AFAIK requires a reboot) just to run some SqlFu tests. It's much easier to just change the connection string directly and then change it back.
