### ISSUE TITLE
Table config without attributes

### ISSUE THREAD

**Issue by sapatag** [sapiens/SqlFu#82]
Dear Developer,
I have used SqlFu in some personal projects, and I'm loving it!
Howewer I'm not a fan of the Table attrib, so I made TableInfo public and added some methods like:
```c#
public TableInfo SetPrimaryKey(string fieldName, bool autogenerated)
    {
        PrimaryKey = fieldName;
        AutoGenerated = autogenerated;
        return this;
    }
```
With this I'm able to do:
```
TableInfo.ForType(typeof(B_DATUMOK)).SetPrimaryKey("DTAZON", true);
```
in my db service init without touching old tables and old pocos.

**Comment by sapiens** [comment]
I'm going to release v3 Beta this week which has this feature. v2 wil become legacy pretty soon.

**Comment by sapatag** [comment]
Thanks!

My other small hack to avoiding `IgnoreAttribute` is 
````c#
    var ig = p.GetSingleAttribute<IgnoreAttribute>(true);
    if (ig == null && p.CanWrite)
`````
in `public TableInfo(Type t)`
