### ISSUE TITLE
Typo bug in DbProvider.EscapeTableName

### ISSUE THREAD

**Issue by gideonkorir** [sapiens/SqlFu#89]
Keep getting System.FormatException when I specify the table schema either using conventions or TableAttribute. Tracked the culprit to EscapeTableName:

```C#
public string EscapeTableName(TableName table)
        {
            var schema = "";
            if (!table.Schema.IsNullOrEmpty())
            {
                schema = Escape(schema,EscapeChars.Start,EscapeChars.End)+".";
            }

            return schema + Escape(table.Name,EscapeChars.Start, EscapeChars.End);
        }
```
After we check that table.Schema is not null or empty, we try and escape the empty schema variable which causes us to throw

**Comment by sapiens** [comment]
Thanks, ver 3.3.2 contains the PR.
