### ISSUE TITLE
 at run time how create a dynamic table , add columns

### ISSUE THREAD

**Issue by smartmeter** [sapiens/SqlFu#92]
Hello, this is a very nice lib :+1: 

I was looking at the wiki, but need help on how to create that table at runtime.

For e.g. I am parsing / **reading a list of columns from a text file or excel, and then trying to add those column names to the SqlFu to create the table** at runtime.

> ColName Type
> Name   - varchar
> Phone   -   int
> DOB     -  datetime

thanks

**Comment by sapiens** [comment]
SqlFu has no explicit support for creating tables at runtime. You just use a string builder to create the sql command then execute it.

**Comment by sapiens** [comment]
SqlFu has no explicit support for creating tables at runtime. You just use a string builder to create the sql command then execute it.
