### ISSUE TITLE
Adding support for date-related sql functions

### ISSUE THREAD

**Issue by preslavnd** [sapiens/SqlFu#94]
Currently we are migrating some queries from Entity Framework and among other things we need, is support for functions like dateadd, diffyears, diffdays. Do you have any plans on implementing these?

**Comment by sapiens** [comment]
Not in the near future (too busy).

**Comment by sapiens** [comment]
Not in the near future (too busy).

**Comment by sapiens** [comment]
I've written a [tutorial](https://github.com/sapiens/SqlFu/wiki/Adding-support-for-sql-functions) on how to implement builder support for any sql function you want
