### ISSUE TITLE
Could you write a version 2 to version 3 migration procedure?

### ISSUE THREAD

**Issue by Ephasme** [sapiens/SqlFu#95]
I'm currently in version 2 and I tried to migrate to version 3 but I really don't want to rewrite everything I wrote in version 3, can you write a migration notice as you did for 1 to 2? Thanks.

**Comment by sapiens** [comment]
You don't need to rewrite everything, only some configuration bits. But, I will write a guide as soon as a I have some time

**Comment by sapiens** [comment]
Done https://github.com/sapiens/SqlFu/wiki/Upgrading-from-v2-to-v3 . It's a bit hasty, but that's how it is :)
