### ISSUE TITLE
Inserting a record into table with rowversion column in v3.3.5

### ISSUE THREAD

**Issue by Razhenkov** [sapiens/SqlFu#98]
We have a table with rowversion column. When we try to insert a record, we receive the following exception:

> Cannot insert an explicit value into a timestamp column. Use INSERT with a colimn list to exclude the timestamp column, or insert a DEFAULT into the timestamp column.

The problem should be solved with [QueryOnly] attribute, which is available in version 2 but is missing in the last version. How can we fix the problem? Is it possible to return [QueryOnly] attribute?

**Comment by sapiens** [comment]
SqlServer type rowversion should be a byte[8] property of the POCO.

**Comment by Razhenkov** [comment]
Yes, we use byte[8] property, but rowversion is auto-generated type in T-SQL and SqlFu try to set value on this field. The problem is that SqlFu doesn't ignore byte[8] property when do insert operation

**Comment by sapiens** [comment]
Try this
```csharp
 db.Insert(myData,opt=>opt.Ignore(c=>c.Version))
```

or you can remove that property from the POCO all together if you don't use it in your app i.e it's used only by the db.

**Comment by Razhenkov** [comment]
The insert option did the job. Thank you
